# Setup
title:        Robert Loveridge
tagline:      Customer Support Manager
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Robert Loveridge
  url:        http://robertloveridge.co.uk
  location:   Allesley Park, Coventry

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Others
markdown: kramdown
include: ['_pages']
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

remote_theme: pages-themes/minimal@v0.2.0
